#!/usr/bin/env zsh

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow --ignore='^\.post-install$' -D $folder
    stow --ignore='^\.post-install$' $folder
done
popd
