#!/usr/bin/env zsh

# Set DOTFILES variable
if [[ -z $DOTFILES ]]; then
    DOTFILES=./
fi

STOW_FOLDERS=$(find "$DOTFILES" -mindepth 1 -maxdepth 1 -type d ! -name '.git' -exec basename {} \; | paste -sd "," -)

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow --ignore='^\.post-install$' -D $folder -t ~
    stow --ignore='^\.post-install$' $folder -t ~
done
popd
