# Shell / terminal
set -g default-shell /bin/zsh
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Behavior
set -g set-clipboard on
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g mouse on
set -g status-interval 3
set -g allow-passthrough on
set -g visual-activity off

# Indexing
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Status bar
set -g status-position top
set -g status-style bg=default

# Prefix remap
unbind C-b
set -g prefix M-m
bind-key M-m send-prefix

# Reload config
unbind r
bind-key r source-file ~/.config/tmux/tmux.conf

# Copy mode
unbind [
bind v copy-mode

# Window navigation
bind -n M-H previous-window
bind -n M-L next-window

# New window
unbind c
bind c new-window -c "#{pane_current_path}"

# Splits
unbind %
bind % split-window -h -c "#{pane_current_path}"

unbind '"'
bind '"' split-window -v -c "#{pane_current_path}"

# Kill pane without confirmation
bind-key x kill-pane

# sesh session picker
bind-key "t" run-shell "sesh connect \"$(
        sesh list --icons | fzf-tmux -p 55%,60% \
        --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
        --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
        --bind 'tab:down,btab:up' \
        --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
        --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
        --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
        --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
        --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
        --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
        )\""

# Last session
bind -N "last-session (via sesh)" L run-shell "sesh last"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'omerxx/tmux-floax'

# Plugin config
set -g @floax-bind '-n M-Space'
set -g @tmux-gruvbox 'dark'

# TPM (must stay last)
run '$HOME/.config/tmux/plugins/tpm/tpm'
