return {
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    config = function()
      require("mason-tool-installer").setup({
        ensure_installed = {
          "bash-language-server",
          "phpantom_lsp",
          "ty",
          "black",
          "clangd",
          "csharpier",
          "docker-compose-language-service",
          "dockerfile-language-server",
          "eslint-lsp",
          "fantomas",
          "fsautocomplete",
          "gofumpt",
          "goimports",
          "golangci-lint",
          "gopls",
          "hadolint",
          "json-lsp",
          "lua-language-server",
          "markdown-toc",
          "markdownlint-cli2",
          "marksman",
          "netcoredbg",
          "omnisharp",
          "prettier",
          "shellcheck",
          "shfmt",
          "sqlfluff",
          "stylua",
          "tailwindcss-language-server",
          "taplo",
          "tinymist",
          "tree-sitter-cli",
          "ty",
          "vtsls",
          "yaml-language-server",
          "zls",
        },
        auto_update = true,
        run_on_start = true,
      })
    end,
  },
}
